version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2022-gui:current
      resource_class: windows.medium
      shell: bash

jobs:
  Test Checkout:
    executor: windows
    steps:
      - run:
          name: Checkout
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            echo "DEBUG 1"
            cat ~/.ssh/known_hosts
            echo "DEBUG 2"
            ssh-keygen -t ed25519 -C "your_email@example.com"
            echo "DEBUG 3"
            git clone -b "$Env:CIRCLE_BRANCH" "$Env:CIRCLE_REPOSITORY_URL" --depth 1 .

workflows:
  all:
    jobs:
      - Test Checkout
