version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2022-gui:current
      resource_class: windows.medium
      shell: bash

jobs:
  Test Checkout:
    executor: windows
    steps:
      - add_ssh_keys:
          fingerprints:
            - "90:c4:0d:06:71:40:2b:00:67:d9:81:d2:48:45:34:53"
      - run:
          name: Checkout
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            echo "DEBUG 1"
            cat ~/.ssh/known_hosts
            echo "DEBUG 3"
            git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL" --depth 1 .

workflows:
  all:
    jobs:
      - Test Checkout
